services:
  postgis:
    image: postgis/postgis:17-3.5-alpine
    container_name: postgis
    restart: unless-stopped
    environment:
      POSTGRES_DB: gis
      POSTGRES_USER: gisuser
      POSTGRES_PASSWORD: gispass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

  redis:
    image: redis:8.2-rc1
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  tegola:
    image: gospatial/tegola:latest
    container_name: tegola
    depends_on:
      - postgis
      - redis
    restart: unless-stopped
    volumes:
      - ./tegola-config.toml:/config.toml
    command: serve --config /config.toml
    ports:
      - "8080:8080"

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: unless-stopped
    depends_on:
      - postgis
    ports:
      - "8081:8080"

volumes:
  pgdata:
