[webserver]
port = ":8080"

[cache]
type = "redis"
uri = "redis://redis:6379"
max_zoom = 20

[[providers]]
name = "pg_trails"
type = "postgis"
uri = "postgresql://gisuser:gispass@postgis:5432/gis?sslmode=disable"

  [[providers.layers]]
  name = "trails"
  geometry_fieldname = "geom"        
  id_fieldname = "id"                
  geometry_type = "LineString"       
  sql = "SELECT id, name, level, geom FROM trails WHERE geom && !BBOX!"



[[maps]]
name = "trails_map"

  [[maps.layers]]
  provider_layer = "pg_trails.trails"
  min_zoom = 0
  max_zoom = 20
